### ISSUE TITLE
No pods found on cocoapods.org

### ISSUE THREAD

**Issue by 3ign0n** [MO-AI/MOAspects#1]
http://cocoapods.org/?q=MOAspects
It says no pods found.

**Comment by moaible** [comment]
@3ign0n 
Wait a moment please. I'll register MOAspects in [cocoapods](http://cocoapods.org/?q=MOAspects).

**Comment by moaible** [comment]
@3ign0n 
Thank you for waiting. Please `pod install` command!

http://cocoapods.org/?q=MOAspects

**Comment by 3ign0n** [comment]
Awesome!!
