### ISSUE TITLE
Problem with hooking overridden instance methods

### ISSUE THREAD

**Issue by 3ign0n** [MO-AI/MOAspects#5]
This test case is failed.
The hooked usingBlock has never been called for instance methods.
https://gist.github.com/3ign0n/58c9c34ac2c1c5f9a1ff

**Comment by moaible** [comment]
@3ign0n 
I'll see to it right away.

**Comment by moaible** [comment]
@3ign0n 
Thank you for reporting!
There was a bug in MOAspects.m. I fixed that bug and pushed to master (v0.1.3).

**Comment by moaible** [comment]
@3ign0n 

> Thank you for reporting!
> There was a bug in MOAspects.m. I fixed that bug and pushed to master (v0.1.3).

Sorry, master branch still doesn't work.

**Comment by 3ign0n** [comment]
I confirmed v0.1.4 fixes this issue. Thank you.
